version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANG=en_US.utf8
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'

    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d